# Generated by Django 2.2.6 on 2021-01-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_source', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=20)),
                ('product_image_link', models.CharField(max_length=255)),
                ('product_link', models.CharField(max_length=255)),
                ('product_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape_app.ProductSource')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape_app.ProductType')),
            ],
        ),
    ]
