# Generated by Django 2.2.6 on 2021-01-17 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='adddate',
            field=models.DateTimeField(auto_now_add=True, db_column='ADDDATE', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='editdate',
            field=models.DateTimeField(auto_now=True, db_column='EDITDATE'),
        ),
    ]
