# Generated by Django 2.2.6 on 2021-01-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_app', '0002_auto_20210117_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_source',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductSource',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
