# Generated by Django 2.2.6 on 2021-01-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_app', '0003_auto_20210119_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
