# Generated by Django 2.2.6 on 2021-01-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_app', '0004_auto_20210119_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='editdate',
        ),
    ]
